function mex_v1_lib
% compile only the sfunction and link to precompiled
% libraries in the lib-directory
    mex_command = ['mex '...
        '-v '...
        '-I"include" '...
        '-Llib '...
        %'-liir_filter_v1 '...
        '-lmatrixmath '...
        'iir_filter_v1_sfunction.c'...
        ];
    
    eval(mex_command);
end
