function mex_v1_all
% compile matrixmath and fir_filter_v1 on the fly
% and link to the respective object files

    mex_command = [ 'mex ',...
        '-v ',...
        '-Imatrixmath ',...
         '-Iiir_filter_v1 ',...
        'iir_filter_v1_sfunction.c ', ...
        'matrixmath/matrixmath.c ', ...
        'iir_test_filter/iir_filter_v1.c'...
        ]
	eval(mex_command);

end
